//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Proje_Uygulama
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_URUNLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_URUNLER()
        {
            this.TBL_SATIS = new HashSet<TBL_SATIS>();
        }
    
        public int URUN_ID { get; set; }
        public string URUN_AD { get; set; }
        public string URUN_MARKA { get; set; }
        public Nullable<short> URUN_STOK { get; set; }
        public Nullable<decimal> URUN_FIYAT { get; set; }
        public Nullable<bool> URUN_DURUM { get; set; }
        public Nullable<int> URUN_KATEGORİ { get; set; }
    
        public virtual TBL_KATEGORILER TBL_KATEGORILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SATIS> TBL_SATIS { get; set; }
    }
}
